TrajectoryPlannerROS:
  holonomic_robot: false 

  # Velocity limits
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  # Acceleration limits
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  acc_lim_y: 2.5

  # Goal tolerances
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

  # Simulation parameters
  sim_time: 1.7
  vx_samples: 3
  vtheta_samples: 20

  meter_scoring: true