robot_base_frame: base_footprint
transform_tolerance: 2.0

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  max_obstacle_height: 2.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.5

footprint: [[0.145, 0.13], [0.145, -0.13], [-0.145, -0.13], [-0.145, 0.13]]