DWAPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.0
  max_vel_theta: 0.8
  min_vel_theta: -0.8
  min_in_place_vel_theta: 0.3

  # --- GIA T·ªêC ---
  acc_lim_x: 0.5
  acc_lim_theta: 1.0
  acc_lim_y: 0.0

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  vx_samples: 10
  vy_samples: 0
  vth_samples: 20
  path_distance_bias: 32.0     
  goal_distance_bias: 24.0     
  occdist_scale: 0.02 
  
  forward_point_distance: 0.0
  
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  use_dijkstra: true
  oscillation_reset_dist: 0.05