DWAPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  acc_lim_x: 2.5
  acc_lim_theta: 3.5
  acc_lim_y: 0.0

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.3

  sim_time: 3.0  # Thời gian simulate quỹ đạo (giây)
  vx_samples: 20  # Số mẫu vận tốc tuyến tính
  vy_samples: 0   # 0 vì non-holonomic
  vth_samples: 40 # Số mẫu vận tốc góc
  path_distance_bias: 32.0  # Ưu tiên bám sát global path
  goal_distance_bias: 20.0  # Ưu tiên gần goal
  occdist_scale: 0.01       # Trọng số tránh chướng ngại
  forward_point_distance: 0.325  # Điểm forward để đánh giá quỹ đạo
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  max_scaling_factor: 0.2
  use_dijkstra: true  # THÊM: Dùng Dijkstra trong DWA nếu A* fail
  oscillation_reset_dist: 0.05