frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
debug: false
publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom

# ODOMETRY TỪ BÁNH XE (Encoder)
odom0: /odom/wheel

# Ma trận cấu hình: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
odom0_config: [false, false, false,
               false, false, false,
               true,  false, false,   # Chỉ lấy Vx (Vận tốc tới)
               false, false, true,    # Chỉ lấy Vyaw (Vận tốc xoay)
               false, false, false]

odom0_queue_size: 10
odom0_nodelay: true
odom0_differential: false
odom0_relative: false

# INPUT 2: IMU (Gia tốc & Góc quay)
imu0: /imu

# Ma trận cấu hình: [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
imu0_config: [false, false, false,
              true,  true,  true,     # Lấy góc nghiêng (Roll, Pitch, Yaw)
              false, false, false,
              true,  true,  true,     # Lấy vận tốc góc (Roll, Pitch, Yaw rate)
              true,  false, false]    # Lấy gia tốc X (để hỗ trợ phát hiện trượt khi khởi động)

imu0_differential: false
imu0_relative: true           # Reset góc IMU về 0 khi khởi động node
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true