gazebo_ros_control:
  pid_gains:
    left_front_wheel_joint:
      p: 1000.0
      i: 0.0
      d: 10.0
      i_clamp: 0.0
    right_front_wheel_joint:
      p: 1000.0
      i: 0.0
      d: 10.0
      i_clamp: 0.0
    left_rear_wheel_joint:
      p: 1000.0
      i: 0.0
      d: 10.0
      i_clamp: 0.0
    right_rear_wheel_joint:
      p: 1000.0
      i: 0.0
      d: 10.0
      i_clamp: 0.0
